# -*- coding: utf-8 -*-
"""my_app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6Ao8r86nYYh_U0BMf3YFKp6HeS0Bx56
"""



import streamlit as st
import pandas as pd

st.write("My First Streamlit Web App")
df = pd.DataFrame({"one": [1, 2, 3], "two": [4, 5, 6], "three": [7, 8, 9]})
st.write(df)

